metadata:
  product_id: Nats trigger process
  workflow_name: Nats trigger workflow
  process_name: Nats trigger process
  version_tag: Nats trigger version v1.0.0
  base_path: "/Some/Path"

nats:
  url: "nats://localhost:4222"
  stream: nats-trigger
  inputs:
    - exit-output
  output: nats-trigger-output

centralized_configuration:
  global:
    bucket: global
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process