metadata:
  product_id: Demo training product
  workflow_id: Training workflow
  process_id: validation

nats:
  url: 'nats://localhost:4222'
  stream: validation
  output: validation
  inputs: [training-py, trainig-go]

centralized_configuration:
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process
