metadata:
  product_id: Demo training product
  workflow_id: Training workflow
  process_id: github-trigger-mock

nats:
  url: "nats://localhost:4222"
  stream: github-trigger
  output: github-trigger

centralized_configuration:
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process
