# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: training.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etraining.proto\x12\x04main\"1\n\x08Splitter\x12\x13\n\x0btraining_id\x18\x01 \x01(\t\x12\x10\n\x08repo_url\x18\x02 \x01(\t\"1\n\x08Training\x12\x13\n\x0btraining_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\"J\n\nValidation\x12\x13\n\x0btraining_id\x18\x01 \x01(\t\x12\'\n\rmodels_scores\x18\x02 \x03(\x0b\x32\x10.main.ModelScore\"-\n\nModelScore\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\tB\tZ\x07./protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'training_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./proto'
  _SPLITTER._serialized_start=24
  _SPLITTER._serialized_end=73
  _TRAINING._serialized_start=75
  _TRAINING._serialized_end=124
  _VALIDATION._serialized_start=126
  _VALIDATION._serialized_end=200
  _MODELSCORE._serialized_start=202
  _MODELSCORE._serialized_end=247
# @@protoc_insertion_point(module_scope)
