metadata:
  product_id: Trigger product
  version_tag: Trigger version v1.0.0
  workflow_name: Trigger workflow
  workflow_type: training workflow
  process_name: Trigger process

nats:
  url: "nats://localhost:4222"
  stream: trigger
  output: trigger-output
  object_store: ephemeral-storage

minio:
  endpoint: "localhost:9000"
  client_user: "minio_user"
  client_password: "minio_password"
  ssl: false
  bucket: "test-bucket"

auth:
  internal_folder: ".kai"
  endpoint: "http://auth.kai.local"
  client: "kai"
  client_secret: "kai_pwd"
  realm: "konstellation"

predictions:
  endpoint: localhost:6379
  username: default
  password: redispw
  index_key: index

model_registry:
  folder_name: ".models"

measurements:
  endpoint: "localhost:4317"
  insecure: true
  timeout: 5
  metrics_interval: 10

centralized_configuration:
  global:
    bucket: global
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process
    config:
      test1: value1
      test2: value2