metadata:
  product_id: Nats trigger process
  version_tag: Nats trigger version v1.0.0
  workflow_name: Nats trigger workflow
  workflow_type: serving workflow
  process_name: Nats trigger process

nats:
  url: "nats://localhost:4222"
  stream: trigger
  inputs:
    - exit-output
  output: trigger-output
  object_store: ephemeral-storage

minio:
  endpoint: "localhost:9000"
  client_user: "minio_user"
  client_password: "minio_password"
  ssl: false
  bucket: "test-bucket"

auth:
  endpoint: "http://auth.kai.local"
  client: "kai"
  client_secret: "kai_pwd"
  realm: "konstellation"

predictions:
  endpoint: localhost:6379
  username: default
  password: redispw
  index_key: index

centralized_configuration:
  global:
    bucket: global
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process
    config:
      test1: value1
      test2: value2