metadata:
  product_id: Nats trigger process
  workflow_name: Nats trigger workflow
  process_name: Nats trigger process
  version_tag: Nats trigger version v1.0.0
  base_path: "/Some/Path"

nats:
  url: "nats://localhost:4222"
  stream: trigger
  inputs:
    - exit-output
  output: trigger-output
  object_store: ephemeral-storage

minio:
  endpoint: "localhost:9000"
  client_user: user
  client_password: pwd
  ssl: false
  bucket: test-bucket

auth:
  endpoint: "https://auth.kai.local"
  client: minioadmin
  client_secret: minioadmin
  realm: konstellation

centralized_configuration:
  global:
    bucket: global
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process
    config:
      test1: value1
      test2: value2