metadata:
  product_id: Rest trigger process
  workflow_id: Rest trigger workflow
  process_id: Rest trigger process
  version_id: Rest trigger version v1.0.0
  base_path: "/Some/Path"

nats:
  url: "nats://localhost:4222"
  stream: rest-trigger
  inputs:
    - exit-output
  output: rest-trigger-output

centralized_configuration:
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process