metadata:
  product_id: Task process
  workflow_id: Task workflow
  process_id: Task process
  version_id: Task version v1.0.0
  base_path: "/Some/Path"

nats:
  url: "nats://localhost:4222"
  stream: exit
  inputs:
    - task-output
  output: exit-output
  object_store: ephemeral-storage

minio:
  endpoint: "localhost:9000"
  access_key: "minio"
  secret_key: "minio123"
  region: "us-east-1"
  secure: false
  bucket: "test-bucket"

centralized_configuration:
  global:
    bucket: global
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process