runner:
  logger:
    level: DEBUG # TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL
    encoding: console # console, json
    output_paths:
      - json
    error_output_paths:
      - console
