metadata:
  product_id: Exit process
  workflow_name: Exit workflow
  process_name: Exit process
  version_tag: Exit version v1.0.0
  base_path: "/Some/Path"

nats:
  url: "nats://localhost:4222"
  stream: exit
  inputs:
    - task-output
  output: exit-output
  object_store: ephemeral-storage

minio:
  url: "localhost:9000"
  access_key_id: minioadmin
  access_key_secret: minioadmin
  use_ssl: false
  bucket: test-bucket

centralized_configuration:
  global:
    bucket: global
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process
    config:
      test1: value1
      test2: value2