metadata:
  product_id: Exit process
  workflow_id: Exit workflow
  process_id: Exit process
  version_id: Exit version v1.0.0
  base_path: "/Some/Path"

nats:
  url: "nats://localhost:4222"
  stream: exit
  inputs:
    - task-output
  output: exit-output
  object_store: ephemeral-storage

centralized_configuration:
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process
    config:
      test1: value1
      test2: value2