metadata:
  product_id: Exit process
  workflow_id: Exit workflow
  process_id: Exit process
  version_id: Exit version v1.0.0
  base_path: "/Some/Path"

nats:
  url: "nats://localhost:4222"
  stream: exit
  inputs:
    - task-output
  output: exit-output
  object_store: ephemeral-storage

minio:
  endpoint: "localhost:9000"
  access_key: "minio"
  secret_key: "minio123"
  region: "us-east-1"
  secure: false

centralized_configuration:
  global:
    bucket: global
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process
    config:
      test1: value1
      test2: value2