metadata:
  product_id: Exit process
  workflow_id: Exit workflow
  process_id: Exit process
  version_id: Exit version v1.0.0
  base_path: "/Some/Path"

nats:
  url: "nats://192.168.1.155:4222"
  stream: trigger
  inputs:
    - trigger-output
  output: exit-output
  object_store: object-store

centralized_configuration:
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process
    config:
      test: value1
      test2: value2