metadata:
  product_id: Demo training product
  workflow_id: Training workflow
  process_id: splitter

nats:
  url: "nats://localhost:4222"
  stream: splitter
  inputs: github-trigger
  output: splitter

centralized_configuration:
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process