metadata:
  product_id: Trigger product
  workflow_name: Trigger workflow
  process_name: Trigger process
  version_tag: Trigger version v1.0.0

nats:
  url: "nats://localhost:4222"
  stream: trigger
  inputs:
    - exit-output
  output: trigger-output
  object_store: ephemeral-storage

minio:
  internal_folder: ".kai"
  endpoint: "localhost:9000"
  client_user: "minio_user"
  client_password: "minio_password"
  ssl: false
  bucket: "test-bucket"

model_registry:
  folder_name: ".models"

auth:
  endpoint: "http://auth.kai.local"
  client: "kai"
  client_secret: "kai_pwd"
  realm: "konstellation"

centralized_configuration:
  global:
    bucket: global
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process
    config:
      test1: value1
      test2: value2