metadata:
  product_id: Trigger product
  workflow_name: Trigger workflow
  process_name: Trigger process
  version_tag: Trigger version v1.0.0
  base_path: "/Some/Path"

nats:
  url: "nats://localhost:4222"
  stream: trigger
  inputs:
    - exit-output
  output: trigger-output
  object_store: ephemeral-storage

minio:
  endpoint: "localhost:9000"
  access_key: "minio"
  secret_key: "minio123"
  region: "us-east-1"
  secure: false
  bucket: "test-bucket"

centralized_configuration:
  global:
    bucket: global
  product:
    bucket: product
  workflow:
    bucket: workflow
  process:
    bucket: process
    config:
      test1: value1
      test2: value2