name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.5
      - name: Install poetry and dependencies
        run: |
          python -m pip install poetry=="1.7.1"
          python -m poetry install
        working-directory: ./py-sdk
      - name: Add API TOKEN to Poetry
        run: |
          python -m poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        working-directory: ./py-sdk
      - name: Build package
        run: |
          python -m poetry build
        working-directory: ./py-sdk
      - name: Publish package
        run: |
          python -m poetry publish
        working-directory: ./py-sdk

