// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MeasurementsMock is an autogenerated mock type for the measurements type
type MeasurementsMock struct {
	mock.Mock
}

type MeasurementsMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MeasurementsMock) EXPECT() *MeasurementsMock_Expecter {
	return &MeasurementsMock_Expecter{mock: &_m.Mock}
}

// NewMeasurementsMock creates a new instance of MeasurementsMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMeasurementsMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MeasurementsMock {
	mock := &MeasurementsMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
