// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MessageUtilsMock is an autogenerated mock type for the messageUtils type
type MessageUtilsMock struct {
	mock.Mock
}

type MessageUtilsMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageUtilsMock) EXPECT() *MessageUtilsMock_Expecter {
	return &MessageUtilsMock_Expecter{mock: &_m.Mock}
}

// GetMaxMessageSize provides a mock function with given fields:
func (_m *MessageUtilsMock) GetMaxMessageSize() (int64, error) {
	ret := _m.Called()

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageUtilsMock_GetMaxMessageSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxMessageSize'
type MessageUtilsMock_GetMaxMessageSize_Call struct {
	*mock.Call
}

// GetMaxMessageSize is a helper method to define mock.On call
func (_e *MessageUtilsMock_Expecter) GetMaxMessageSize() *MessageUtilsMock_GetMaxMessageSize_Call {
	return &MessageUtilsMock_GetMaxMessageSize_Call{Call: _e.mock.On("GetMaxMessageSize")}
}

func (_c *MessageUtilsMock_GetMaxMessageSize_Call) Run(run func()) *MessageUtilsMock_GetMaxMessageSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MessageUtilsMock_GetMaxMessageSize_Call) Return(_a0 int64, _a1 error) *MessageUtilsMock_GetMaxMessageSize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageUtilsMock_GetMaxMessageSize_Call) RunAndReturn(run func() (int64, error)) *MessageUtilsMock_GetMaxMessageSize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageUtilsMock creates a new instance of MessageUtilsMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageUtilsMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageUtilsMock {
	mock := &MessageUtilsMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
