// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PersistentStorageMock is an autogenerated mock type for the persistentStorage type
type PersistentStorageMock struct {
	mock.Mock
}

type PersistentStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PersistentStorageMock) EXPECT() *PersistentStorageMock_Expecter {
	return &PersistentStorageMock_Expecter{mock: &_m.Mock}
}

// NewPersistentStorageMock creates a new instance of PersistentStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersistentStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersistentStorageMock {
	mock := &PersistentStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
